#!/bin/bash

if command -v stow &> /dev/null
then
    echo "Stows every package"
    for package in $(ls -d */)
    do
        stow $package
    done
else
    echo "You need to install stow to run this script."
fi
